name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installs dependencies from the requirements.txt located inside the API folder
          pip install -r ./app/api/requirements.txt
          pip install flake8 pytest

      - name: Run linter (flake8)
        # Lints the 'app' directory where your API code is
        run: flake8 ./app --count --select=E9,F63,F7,F82 --show-source --statistics
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The context is the root of the repository
          context: ./app/api
          # Specifies the path to the Dockerfile
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-flask-api:latest
